package com.yourname.meetinglistener.utils

import android.content.Context
import android.content.Intent
import android.os.Environment
import androidx.core.content.FileProvider
import com.yourname.meetinglistener.storage.entities.MeetingSummaryEntity
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

/**
 * MeetingExporter.kt
 *
 * PURPOSE:
 * Export meeting MoM to .txt file
 * Allows user to share/download meeting summary
 */
class MeetingExporter(private val context: Context) {

    /**
     * Export meeting to .txt file and open share dialog
     */
    fun exportToTxt(meeting: MeetingSummaryEntity): Intent? {
        try {
            // Create filename
            val dateFormat = SimpleDateFormat("yyyy-MM-dd_HH-mm", Locale.getDefault())
            val date = dateFormat.format(Date(meeting.startTime))
            val filename = "MoM_${date}.txt"

            // Create file in cache directory
            val file = File(context.cacheDir, filename)

            // Write MoM content
            file.writeText(formatMeetingAsTxt(meeting))

            // Create share intent
            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_SUBJECT, "Meeting Minutes - $date")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            return Intent.createChooser(shareIntent, "Export Meeting")

        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }
    }

    /**
     * Format meeting as text
     */
    private fun formatMeetingAsTxt(meeting: MeetingSummaryEntity): String {
        val dateFormat = SimpleDateFormat("MMMM dd, yyyy 'at' HH:mm", Locale.getDefault())
        val date = dateFormat.format(Date(meeting.startTime))

        return buildString {
            appendLine("═══════════════════════════════════════")
            appendLine("        MEETING MINUTES (MoM)")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine("📅 Date: $date")
            appendLine("⏱️ Duration: ${meeting.durationMinutes} minutes")
            appendLine("👤 Participant: ${meeting.userName}")
            appendLine("📝 Transcripts: ${meeting.transcriptCount} segments")
            appendLine()
            appendLine("═══════════════════════════════════════")
            appendLine("📋 SUMMARY")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine(meeting.finalSummary)
            appendLine()
            appendLine("═══════════════════════════════════════")
            appendLine("✅ DECISIONS MADE")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine(meeting.decisions)
            appendLine()
            appendLine("═══════════════════════════════════════")
            appendLine("📌 ACTION ITEMS")
            appendLine("═══════════════════════════════════════")
            appendLine()
            appendLine(meeting.actionItems)
            appendLine()
            appendLine("═══════════════════════════════════════")
            appendLine("Generated by Meeting Listener App")
            appendLine("═══════════════════════════════════════")
        }
    }
}